function onOpen(): void {
  SpreadsheetApp.getUi()
    .createMenu("Rotation")
    .addItem("Set Up Workbook", "menuSetupWorkbook")
    .addSeparator()
    .addItem("Fill Grid for Upcoming Week", "menuFillGrid")
    .addItem("Rotate Rosters", "menuRotateRosters")
    .addSeparator()
    .addItem("Check for Manual Edits", "menuCheckForManualEdits")
    .addToUi();
}

function requireConfigSheet(
  ui: GoogleAppsScript.Base.Ui
): GoogleAppsScript.Spreadsheet.Sheet | null {
  const sheet = getSpreadsheet().getSheetByName(CONFIG_SHEET_NAME);
  if (!sheet) {
    ui.alert(
      "No Config sheet yet",
      'Use "Rotation > Set Up Workbook" first.',
      ui.ButtonSet.OK
    );
    return null;
  }
  return sheet;
}

function showError(ui: GoogleAppsScript.Base.Ui, e: unknown): void {
  const message = e instanceof Error ? e.message : String(e);
  ui.alert("Error", message, ui.ButtonSet.OK);
}

function menuSetupWorkbook(): void {
  const ui = SpreadsheetApp.getUi();
  try {
    setupWorkbook();
  } catch (e) {
    showError(ui, e);
  }
}

function menuFillGrid(): void {
  const ui = SpreadsheetApp.getUi();
  try {
    const configSheet = requireConfigSheet(ui);
    if (!configSheet) {
      return;
    }
    const scheduleSheet = getOrCreateSheet(SCHEDULE_SHEET_NAME);

    if (isScheduleDirty(scheduleSheet)) {
      const response = ui.alert(
        "Schedule has manual edits",
        "The Schedule sheet looks like it was hand-edited since it was last generated. Filling the grid now will overwrite those changes. Continue?",
        ui.ButtonSet.YES_NO
      );
      if (response !== ui.Button.YES) {
        return;
      }
    }

    const config = readConfig(configSheet);
    const assignment = computeAssignments(config);

    if (assignment.errors.length > 0) {
      ui.alert("Can't fill the grid", assignment.errors.join("\n"), ui.ButtonSet.OK);
      return;
    }
    if (assignment.orderedDays.length === 0) {
      ui.alert(
        "Nothing to fill",
        "No days are marked as included on the Config sheet. Check at least one day's box and try again.",
        ui.ButtonSet.OK
      );
      return;
    }

    writeSchedule(scheduleSheet, config, assignment);
    getSpreadsheet().setActiveSheet(scheduleSheet);

    ui.alert(
      "Schedule updated",
      "The grid has been filled for the week of " + formatSheetDate(config.startDate) + ".",
      ui.ButtonSet.OK
    );
  } catch (e) {
    showError(ui, e);
  }
}

function menuRotateRosters(): void {
  const ui = SpreadsheetApp.getUi();
  try {
    const configSheet = requireConfigSheet(ui);
    if (!configSheet) {
      return;
    }
    const rotatedDays = rotateRosters(configSheet);
    if (rotatedDays.length === 0) {
      ui.alert(
        "Nothing rotated",
        "No included day has a roster with more than one person to rotate.",
        ui.ButtonSet.OK
      );
    } else {
      ui.alert(
        "Rosters rotated",
        "Rotated: " +
          rotatedDays.join(", ") +
          '.\nUse "Fill Grid for Upcoming Week" to apply the new order to the schedule.',
        ui.ButtonSet.OK
      );
    }
  } catch (e) {
    showError(ui, e);
  }
}

function menuCheckForManualEdits(): void {
  const ui = SpreadsheetApp.getUi();
  try {
    const scheduleSheet = getSpreadsheet().getSheetByName(SCHEDULE_SHEET_NAME);
    if (!scheduleSheet) {
      ui.alert(
        "No schedule yet",
        'Use "Rotation > Fill Grid for Upcoming Week" first.',
        ui.ButtonSet.OK
      );
      return;
    }
    if (isScheduleDirty(scheduleSheet)) {
      ui.alert(
        "Manual edits detected",
        "The Schedule sheet has been changed by hand since it was last generated by this script.",
        ui.ButtonSet.OK
      );
    } else {
      ui.alert(
        "No manual edits",
        "The Schedule sheet matches what this script last generated.",
        ui.ButtonSet.OK
      );
    }
  } catch (e) {
    showError(ui, e);
  }
}
