function gridKey(station: string, dayIndex: number): string {
  return station + "" + dayIndex;
}

function addDays(date: Date, days: number): Date {
  const result = new Date(date.getTime());
  result.setDate(result.getDate() + days);
  return result;
}

// Builds the upcoming week's day/station/person assignments from the
// Config data. Days run in calendar order starting at startDate (not
// Sunday-Saturday order), so e.g. a Wednesday start date with Mon/Wed/Fri
// selected produces Wed, Fri, then next Mon.
function computeAssignments(config: WorkbookConfig): ScheduleAssignment {
  const startDayIndex = config.startDate.getDay();
  const errors: string[] = [];

  const includedDays = config.days.filter(function (d) {
    return d.included;
  });

  const withOffsets = includedDays.map(function (d) {
    const offset = (d.dayIndex - startDayIndex + 7) % 7;
    return { day: d, offset: offset };
  });
  withOffsets.sort(function (a, b) {
    return a.offset - b.offset;
  });

  const orderedDays: ScheduledDay[] = [];
  const stationOrder: string[] = [];
  const grid: { [key: string]: string } = {};

  withOffsets.forEach(function (entry) {
    const d = entry.day;
    if (d.stations.length === 0 && d.roster.length === 0) {
      errors.push(
        d.dayName + " is included but has no roster or stations configured."
      );
      return;
    }
    if (d.stations.length === 0) {
      errors.push(d.dayName + " has a roster but no stations listed.");
      return;
    }
    if (d.roster.length === 0) {
      errors.push(d.dayName + " has stations but no roster listed.");
      return;
    }

    orderedDays.push({
      dayIndex: d.dayIndex,
      dayName: d.dayName,
      date: addDays(config.startDate, entry.offset),
      roster: d.roster,
      stations: d.stations,
    });

    d.stations.forEach(function (station, i) {
      if (stationOrder.indexOf(station) === -1) {
        stationOrder.push(station);
      }
      const person = d.roster[i % d.roster.length];
      grid[gridKey(station, d.dayIndex)] = person;
    });
  });

  return { orderedDays: orderedDays, stationOrder: stationOrder, grid: grid, errors: errors };
}

function formatDayHeader(day: ScheduledDay): string {
  const tz = getSpreadsheet().getSpreadsheetTimeZone();
  return day.dayName + "\n" + Utilities.formatDate(day.date, tz, "M/d/yyyy");
}

function writeSchedule(
  sheet: GoogleAppsScript.Spreadsheet.Sheet,
  config: WorkbookConfig,
  assignment: ScheduleAssignment
): void {
  clearSheet(sheet);

  const tz = getSpreadsheet().getSpreadsheetTimeZone();
  sheet.getRange(1, 1).setValue(
    "Schedule — Week of " + Utilities.formatDate(config.startDate, tz, "M/d/yyyy")
  );
  sheet.getRange(1, 1).setFontWeight("bold").setFontSize(12);

  const headerRow = 2;
  const numCols = assignment.orderedDays.length + 1;
  sheet.getRange(headerRow, 1).setValue("Station");
  assignment.orderedDays.forEach(function (day, i) {
    sheet.getRange(headerRow, i + 2).setValue(formatDayHeader(day));
  });
  sheet
    .getRange(headerRow, 1, 1, numCols)
    .setFontWeight("bold")
    .setWrap(true)
    .setHorizontalAlignment("center");

  assignment.stationOrder.forEach(function (station, rowOffset) {
    const row = headerRow + 1 + rowOffset;
    sheet.getRange(row, 1).setValue(station);
    assignment.orderedDays.forEach(function (day, colOffset) {
      const person = assignment.grid[gridKey(station, day.dayIndex)] || "";
      sheet.getRange(row, colOffset + 2).setValue(person);
    });
  });

  sheet.setFrozenRows(headerRow);
  sheet.setFrozenColumns(1);
  sheet.autoResizeColumns(1, numCols);

  saveScheduleSnapshot(sheet);
}

function getScheduleSnapshot(sheet: GoogleAppsScript.Spreadsheet.Sheet): string {
  const lastRow = sheet.getLastRow();
  const lastCol = sheet.getLastColumn();
  if (lastRow === 0 || lastCol === 0) {
    return "";
  }
  return JSON.stringify(sheet.getRange(1, 1, lastRow, lastCol).getValues());
}

function saveScheduleSnapshot(sheet: GoogleAppsScript.Spreadsheet.Sheet): void {
  PropertiesService.getDocumentProperties().setProperty(
    SCHEDULE_SNAPSHOT_PROPERTY,
    getScheduleSnapshot(sheet)
  );
}

// True only when the Schedule sheet has previously been generated by this
// script AND its current contents no longer match what was last written
// (i.e. someone hand-edited the printed grid since).
function isScheduleDirty(sheet: GoogleAppsScript.Spreadsheet.Sheet): boolean {
  const saved = PropertiesService.getDocumentProperties().getProperty(
    SCHEDULE_SNAPSHOT_PROPERTY
  );
  if (!saved) {
    return false;
  }
  return saved !== getScheduleSnapshot(sheet);
}
