function gridKey(station: string, dayIndex: number): string {
  return station + dayIndex;
}

// Builds the upcoming week's day/station/person assignments from the
// Config data. Days run in calendar order starting at startDate (not
// Sunday-Saturday order), so e.g. a Wednesday start date with Mon/Wed/Fri
// selected produces Wed, Fri, then next Mon.
function computeAssignments(config: WorkbookConfig): ScheduleAssignment {
  const tz = getSpreadsheetTz();
  const startDayIndex = getWeekdayIndex(config.startDate, tz);
  const errors: string[] = [];

  const includedDays = config.days.filter(function (d) {
    return d.included;
  });

  const withOffsets = includedDays.map(function (d) {
    const offset = (d.dayIndex - startDayIndex + 7) % 7;
    return { day: d, offset: offset };
  });
  withOffsets.sort(function (a, b) {
    return a.offset - b.offset;
  });

  const orderedDays: ScheduledDay[] = [];
  const stationOrder: string[] = [];
  const grid: { [key: string]: string } = {};

  withOffsets.forEach(function (entry) {
    const d = entry.day;
    if (d.stations.length === 0 && d.roster.length === 0) {
      errors.push(
        d.dayName + " is included but has no roster or stations configured."
      );
      return;
    }
    if (d.stations.length === 0) {
      errors.push(d.dayName + " has a roster but no stations listed.");
      return;
    }
    if (d.roster.length === 0) {
      errors.push(d.dayName + " has stations but no roster listed.");
      return;
    }
    const duplicateStations = d.stations.filter(function (s, i) {
      return d.stations.indexOf(s) !== i;
    });
    if (duplicateStations.length > 0) {
      errors.push(
        d.dayName +
          " lists " +
          Array.from(new Set(duplicateStations)).join(", ") +
          " more than once. Station names must be unique within a day."
      );
      return;
    }

    orderedDays.push({
      dayIndex: d.dayIndex,
      dayName: d.dayName,
      date: addCalendarDays(config.startDate, tz, entry.offset),
      roster: d.roster,
      stations: d.stations,
    });

    d.stations.forEach(function (station, i) {
      if (stationOrder.indexOf(station) === -1) {
        stationOrder.push(station);
      }
      const person = d.roster[i % d.roster.length];
      grid[gridKey(station, d.dayIndex)] = person;
    });
  });

  return { orderedDays: orderedDays, stationOrder: stationOrder, grid: grid, errors: errors };
}

function formatDayHeader(day: ScheduledDay): string {
  return day.dayName + "\n" + formatSheetDate(day.date);
}

function writeSchedule(
  sheet: GoogleAppsScript.Spreadsheet.Sheet,
  config: WorkbookConfig,
  assignment: ScheduleAssignment
): void {
  clearSheet(sheet);

  sheet.getRange(1, 1).setValue("Schedule — Week of " + formatSheetDate(config.startDate));
  sheet.getRange(1, 1).setFontWeight("bold").setFontSize(12);

  const headerRow = 2;
  const numCols = assignment.orderedDays.length + 1;
  const headerValues = ["Station"].concat(
    assignment.orderedDays.map(formatDayHeader)
  );
  sheet.getRange(headerRow, 1, 1, numCols).setValues([headerValues]);
  sheet
    .getRange(headerRow, 1, 1, numCols)
    .setFontWeight("bold")
    .setWrap(true)
    .setHorizontalAlignment("center");

  if (assignment.stationOrder.length > 0) {
    const gridRows = assignment.stationOrder.map(function (station) {
      const row = [station];
      assignment.orderedDays.forEach(function (day) {
        row.push(assignment.grid[gridKey(station, day.dayIndex)] || "");
      });
      return row;
    });
    sheet
      .getRange(headerRow + 1, 1, gridRows.length, numCols)
      .setValues(gridRows);
  }

  sheet.setFrozenRows(headerRow);
  sheet.setFrozenColumns(1);
  sheet.autoResizeColumns(1, numCols);

  saveScheduleSnapshot(sheet);
}

function getScheduleSnapshot(sheet: GoogleAppsScript.Spreadsheet.Sheet): string {
  const lastRow = sheet.getLastRow();
  const lastCol = sheet.getLastColumn();
  if (lastRow === 0 || lastCol === 0) {
    return "";
  }
  const json = JSON.stringify(sheet.getRange(1, 1, lastRow, lastCol).getValues());
  // Hash rather than store the raw JSON: Document Properties cap each value
  // at 9KB, which a large grid could exceed.
  const digest = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, json);
  return Utilities.base64Encode(digest);
}

function saveScheduleSnapshot(sheet: GoogleAppsScript.Spreadsheet.Sheet): void {
  PropertiesService.getDocumentProperties().setProperty(
    SCHEDULE_SNAPSHOT_PROPERTY,
    getScheduleSnapshot(sheet)
  );
}

// True only when the Schedule sheet has previously been generated by this
// script AND its current contents no longer match what was last written
// (i.e. someone hand-edited the printed grid since). An empty sheet (e.g.
// the user deleted the tab and a fresh blank one was just created) is never
// considered dirty, since there is no manual content at risk of being lost.
function isScheduleDirty(sheet: GoogleAppsScript.Spreadsheet.Sheet): boolean {
  const saved = PropertiesService.getDocumentProperties().getProperty(
    SCHEDULE_SNAPSHOT_PROPERTY
  );
  if (!saved) {
    return false;
  }
  const current = getScheduleSnapshot(sheet);
  if (current === "") {
    return false;
  }
  return saved !== current;
}
