function gridKey(station: string, dayIndex: number): string {
  return station + dayIndex;
}

// Builds the upcoming week's day/person assignments from the Config data.
// Stations are a single global list (already validated unique by
// readStationsFromValues), applied in the same order to every included day.
// Days run in calendar order starting at startDate (not Sunday-Saturday
// order), so e.g. a Wednesday start date with Mon/Wed/Fri selected produces
// Wed, Fri, then next Mon.
function computeAssignments(config: WorkbookConfig): ScheduleAssignment {
  const tz = getSpreadsheetTz();
  const startDayIndex = getWeekdayIndex(config.startDate, tz);
  const errors: string[] = [];

  if (config.stations.length === 0) {
    errors.push("No stations are configured. Add at least one station to the Config sheet.");
    return { orderedDays: [], stationOrder: [], grid: {}, errors: errors };
  }

  const includedDays = config.days.filter(function (d) {
    return d.included;
  });

  const withOffsets = includedDays.map(function (d) {
    const offset = (d.dayIndex - startDayIndex + 7) % 7;
    return { day: d, offset: offset };
  });
  withOffsets.sort(function (a, b) {
    return a.offset - b.offset;
  });

  const orderedDays: ScheduledDay[] = [];
  const grid: { [key: string]: string } = {};

  withOffsets.forEach(function (entry) {
    const d = entry.day;
    if (d.roster.length === 0) {
      errors.push(d.dayName + " is included but has no roster listed.");
      return;
    }

    orderedDays.push({
      dayIndex: d.dayIndex,
      dayName: d.dayName,
      date: addCalendarDays(config.startDate, tz, entry.offset),
    });

    config.stations.forEach(function (station, i) {
      grid[gridKey(station, d.dayIndex)] = d.roster[i % d.roster.length];
    });
  });

  return { orderedDays: orderedDays, stationOrder: config.stations, grid: grid, errors: errors };
}

function formatDayHeader(day: ScheduledDay): string {
  return day.dayName + "\n" + formatSheetDate(day.date);
}

// The size of the rectangle (from A1) that writeSchedule will (re)write for
// a given assignment: the title row, the header row, and one row per
// station.
function scheduleGridDimensions(assignment: ScheduleAssignment): { totalRows: number; numCols: number } {
  return {
    totalRows: 2 + assignment.stationOrder.length,
    numCols: assignment.orderedDays.length + 1,
  };
}

function readScheduleSnapshot(): ScheduleSnapshot | null {
  const raw = PropertiesService.getDocumentProperties().getProperty(SCHEDULE_SNAPSHOT_PROPERTY);
  if (!raw) {
    return null;
  }
  try {
    return JSON.parse(raw) as ScheduleSnapshot;
  } catch (e) {
    return null;
  }
}

function computeGridHash(sheet: GoogleAppsScript.Spreadsheet.Sheet, rows: number, cols: number): string {
  if (rows <= 0 || cols <= 0 || sheet.getMaxRows() < rows || sheet.getMaxColumns() < cols) {
    return "";
  }
  const json = JSON.stringify(sheet.getRange(1, 1, rows, cols).getValues());
  // Hash rather than store the raw JSON: Document Properties cap each value
  // at 9KB, which a large grid could exceed.
  const digest = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, json);
  return Utilities.base64Encode(digest);
}

function saveScheduleSnapshot(sheet: GoogleAppsScript.Spreadsheet.Sheet, rows: number, cols: number): void {
  const snapshot: ScheduleSnapshot = { rows: rows, cols: cols, hash: computeGridHash(sheet, rows, cols) };
  PropertiesService.getDocumentProperties().setProperty(
    SCHEDULE_SNAPSHOT_PROPERTY,
    JSON.stringify(snapshot)
  );
}

// True only when the Schedule sheet has previously been generated by this
// script AND the exact rectangle it last wrote no longer matches (i.e.
// someone hand-edited the printed grid since). This only ever looks at that
// rectangle, so unrelated content elsewhere on the sheet (e.g. announcements
// below the grid) never counts as a manual edit. An empty sheet (cleared, or
// deleted and recreated) is never flagged either, since there's no manual
// content left to protect.
function isScheduleDirty(sheet: GoogleAppsScript.Spreadsheet.Sheet): boolean {
  const saved = readScheduleSnapshot();
  if (!saved || sheet.getLastRow() === 0) {
    return false;
  }
  const currentHash = computeGridHash(sheet, saved.rows, saved.cols);
  if (currentHash === "") {
    return false;
  }
  return currentHash !== saved.hash;
}

// True when (re)writing this assignment would grow the grid into rows or
// columns beyond what the last generation covered, and some of those cells
// already hold content — e.g. the grid gained a station or a day and would
// now overlap hand-maintained content (announcements, notes) that used to
// sit safely below or beside it. isScheduleDirty can't catch this on its
// own, since it only ever compares the previously-known rectangle.
function wouldOverwriteContentOutsideGrid(
  sheet: GoogleAppsScript.Spreadsheet.Sheet,
  assignment: ScheduleAssignment
): boolean {
  const { totalRows, numCols } = scheduleGridDimensions(assignment);
  const previous = readScheduleSnapshot();
  const prevRows = previous ? previous.rows : 0;
  const prevCols = previous ? previous.cols : 0;
  if (totalRows <= prevRows && numCols <= prevCols) {
    return false;
  }

  const checkRows = Math.min(Math.max(totalRows, prevRows), sheet.getLastRow());
  const checkCols = Math.min(Math.max(numCols, prevCols), sheet.getLastColumn());
  if (checkRows <= 0 || checkCols <= 0) {
    return false;
  }

  const values = sheet.getRange(1, 1, checkRows, checkCols).getValues();
  for (let r = 0; r < checkRows; r++) {
    for (let c = 0; c < checkCols; c++) {
      if (r < prevRows && c < prevCols) {
        continue; // already covered by the ordinary hand-edit ("dirty") check
      }
      if (normalizeCell(values[r][c]) !== "") {
        return true;
      }
    }
  }
  return false;
}

function writeSchedule(sheet: GoogleAppsScript.Spreadsheet.Sheet, assignment: ScheduleAssignment): void {
  const { totalRows, numCols } = scheduleGridDimensions(assignment);
  const titleRow = 1;
  const headerRow = 2;
  const gridRows = assignment.stationOrder.length;

  // Only clear the rectangle this script owns (the title, header, and
  // station rows), unioned with whatever extent was written last time, so a
  // shrinking grid doesn't leave stale cells behind. Anything below or
  // beside that — e.g. announcements the user maintains by hand — is left
  // untouched (see wouldOverwriteContentOutsideGrid, checked by callers
  // before this runs).
  const previous = readScheduleSnapshot();
  let clearRows: number;
  let clearCols: number;
  if (previous) {
    clearRows = Math.max(totalRows, Math.min(previous.rows, sheet.getMaxRows()));
    clearCols = Math.max(numCols, Math.min(previous.cols, sheet.getMaxColumns()));
  } else if (PropertiesService.getDocumentProperties().getProperty(LEGACY_SCHEDULE_SNAPSHOT_PROPERTY)) {
    // Upgrading from a version with no {rows,cols,hash} snapshot at all: that
    // version always cleared the *whole* sheet before writing, so nothing but
    // script-owned content could have survived here. Clear everything once so
    // no stale row/column from that version lingers, then start tracking the
    // new, scoped snapshot below.
    clearRows = Math.max(totalRows, sheet.getLastRow());
    clearCols = Math.max(numCols, sheet.getLastColumn());
  } else {
    clearRows = totalRows;
    clearCols = numCols;
  }
  PropertiesService.getDocumentProperties().deleteProperty(LEGACY_SCHEDULE_SNAPSHOT_PROPERTY);

  if (clearRows > 0 && clearCols > 0) {
    const clearRange = sheet.getRange(1, 1, clearRows, clearCols);
    // clear() does not unmerge cells on its own; without this, a title
    // merged across a different number of columns last time (a week with a
    // different day count) can leave a stale merge that the new merge()
    // below overlaps and rejects.
    clearRange.breakApart();
    clearRange.clear();
  }

  const titleRange = sheet.getRange(titleRow, 1, 1, numCols);
  titleRange.merge();
  sheet
    .getRange(titleRow, 1)
    .setValue(SCHEDULE_TITLE)
    .setFontWeight("bold")
    .setFontSize(24)
    .setFontColor("#1155CC")
    .setHorizontalAlignment("center")
    .setVerticalAlignment("middle");
  sheet.setRowHeight(titleRow, 50);

  const headerValues = [""].concat(assignment.orderedDays.map(formatDayHeader));
  const headerRange = sheet.getRange(headerRow, 1, 1, numCols);
  headerRange.setValues([headerValues]);
  headerRange
    .setFontWeight("bold")
    .setWrap(true)
    .setHorizontalAlignment("center")
    .setVerticalAlignment("middle")
    .setBackground("#D9D9D9")
    .setBorder(true, true, true, true, true, true);

  if (gridRows > 0) {
    const gridValues = assignment.stationOrder.map(function (station) {
      const row: string[] = [station];
      assignment.orderedDays.forEach(function (day) {
        row.push(assignment.grid[gridKey(station, day.dayIndex)] || "");
      });
      return row;
    });
    const bodyRange = sheet.getRange(headerRow + 1, 1, gridRows, numCols);
    bodyRange.setValues(gridValues);
    bodyRange
      .setFontWeight("bold")
      .setVerticalAlignment("middle")
      .setBorder(true, true, true, true, true, true);

    const stationColors = assignment.stationOrder.map(function (_, i) {
      return [STATION_ROW_COLORS[i % STATION_ROW_COLORS.length]];
    });
    sheet.getRange(headerRow + 1, 1, gridRows, 1).setBackgrounds(stationColors);
  }

  sheet.setFrozenRows(headerRow);
  sheet.setFrozenColumns(1);
  sheet.autoResizeColumns(1, numCols);

  saveScheduleSnapshot(sheet, totalRows, numCols);
}
